### ISSUE TITLE
🚀 [feature] 상품 등록 API 구현

### ISSUE THREAD

**Issue by GyuHyeokjjookki** [THEGOODs-repo/server#15]
# 🤖 기능 개요
상품 등록 api 구현

## ✅ Todo
- [x] 상품 등록 api 구현
- [x] Api Swagger 명세
- [x] jwt token 설정
- [x] validation &  annotation 설정
