### ISSUE TITLE
🚀 [feature] 상품 정보 수정 API & 상품 상세 정보 조회 API 구현

### ISSUE THREAD

**Issue by GyuHyeokjjookki** [THEGOODs-repo/server#31]
# 🤖 기능 개요
상품의 상세 정보를 수정하는 API 입니다.

## ✅ Todo
- [x] 상품 상세 정보 수정 API 구현
- [x] 상품 상세 정보 조회 API 구현
- [x] Swagger API 명세서 작성
- [x] Jwt 적용

### 📚 Remarks
정보 수정을 위해 정보 조회가 우선적으로 개발해야 해서 두 가지를 동시에 진행하겠습니다.
