### ISSUE TITLE
🚀 [feature] 상품 검색 기능 API 구현

### ISSUE THREAD

**Issue by GyuHyeokjjookki** [THEGOODs-repo/server#65]
# 🤖 기능 개요
상품을 상품 이름별, 태그별, 카테고리별, 판매자 별로 검색하는 API

## ✅ Todo
- [x] 상품명으로 상품 검색 API 구현
- [x] 상품 태그로 상품 검색 API 구현
- [x] 상품 카테고리로 상품 검색 API 구현
- [x] 상품 판매자명으로 상품 검색 API 구현
- [x] Swagger API 명세
- [x] Jwt 작성
