### ISSUE TITLE
🚀 [feature] 선호도 조사 관련 api 구현

### ISSUE THREAD

**Issue by hyoungj00n** [THEGOODs-repo/server#79]
# 🤖 기능 개요
선호도 조사에서 선택된 상품들의 tag들을 모아서 선호도 조사 db에 저장

## ✅ Todo
- [ ] 선호도 조사의 상품들을 불러오는 api
- [ ] 상품의 tag들을 취합하는 api
- [ ] 수집된 tag들을 조회할 수 있는 api
