### ISSUE TITLE
🚀 [feature] Spring Security, jwt 세팅, 로그인 & 회원가입 구현

### ISSUE THREAD

**Issue by hyoungj00n** [THEGOODs-repo/server#8]
# 🤖 기능 개요
Spring Security 설정을 하고 jwt 생성하는 기능 구현

## ✅ Todo
- [x] Spring security 설정 코드 작성
- [x] jwt 생성 코드 작성
- [x] 로그인 & 회원가입 구현
- [x] swagger 설명
- [x] validate 처리
