### ISSUE TITLE
🚀 [feature] 신상품, 마감임박상품, 인기상품 조회 API 구현

### ISSUE THREAD

**Issue by Eunjin3395** [THEGOODs-repo/server#99]
# 🤖 기능 개요

신상품 조회, 마감임박상품 조회, 인기사움 조회 API 구현

## ✅ Todo
- [ ] 신상품 조회 API 구현
- [ ] 마감임박상품 조회 API 구현
- [ ] 인기상품 조회 API 구현
- [ ] Swagger API 명세
- [ ] Validation
